### ISSUE TITLE
Swagger Interface not working via Tunnel Relay

### ISSUE THREAD

**Issue by codeputer** [OfficeDev/microsoft-teams-tunnelrelay#32]
I thought I would post this issue as I think I know what the issue is, but not sure why its an issue.  If a build a OpenAPI/Swagger interface in my web site, it all works great.  Then I try to get the same Swagger/index.HTML, and it does not display via the Tunnel Relay.  

I think I know the issue is with the JavaScript asking for more resources, but I'm not a Javascript guy and hence, as Index.HTML is dynamically generated - not sure where this issue sits.

All  I know is that I would like to expose the Swagger/OpenAPI via a public endpoint for initial integration testing.  Rather than wait for a deploy cycle each time, I want to interact directly with my desktop, using Tunnel Relay.

Can somebody give this a quick view and even tell me where the error is?

Regards,
Richard

**Comment by RamjotSingh** [comment]
You are essentially hitting https://github.com/OfficeDev/microsoft-teams-tunnelrelay/issues/23. Webservers have a habbit of assuming they are always hosted at root (there are reasons for it too, but story for another time). TunnelRelay however the way Azure Relay works cannot host a site at it's root. The issue above talks about a solution for it. Since it's not done yet. A cheap solution for you would be to provision a FrontDoor resource in Azure and point it to your TunnelRelay url. That way FrontDoor will perform the translations for you and add the url segment while presenting a unified root url. Let me know if this helps.

**Comment by codeputer** [comment]
Suggest close and referral to issue #23

**Comment by codeputer** [comment]
Thank you for the quick response!
